import {describe,it,expect} from "vitest";
import {env} from "cloudflare:test";
let seq=0;const tenant=()=>`ft_membership_${Date.now()}_${seq++}`;
async function raw(t:string,op:string,args:any={}){const res=await env.TENANT.get(env.TENANT.idFromName(t)).fetch("https://tenant.test/",{method:"POST",body:JSON.stringify({op,...args})});return {res,body:await res.json<any>()};}
async function bootstrap(t:string){return raw(t,"bootstrapMembers",{kind:"team",displayName:"Team",bootstrappedFrom:"fresh",claimantClerkUserId:"u_owner",members:[{clerkUserId:"u_owner",email:"owner@example.com",role:"owner",state:"active"}]});}
const actor={clerkUserId:"u_owner",memberId:"",label:"owner@example.com"};
describe("native TenantDO membership authority",()=>{
it("invites, binds, and denies disabled identities",async()=>{const t=tenant();const boot=await bootstrap(t);actor.memberId=boot.body.members[0].id;const invited=await raw(t,"inviteMember",{email:"Member@Example.com",role:"member",actor});expect(invited.res.status).toBe(200);const replay=await raw(t,"inviteMember",{email:"member@example.com",role:"member",actor});expect(replay.body.member.id).toBe(invited.body.member.id);const bound=await raw(t,"bindIdentity",{clerkUserId:"u_member",emails:["member@example.com"],source:"test"});expect(bound.body.member.state).toBe("active");const disabled=await raw(t,"setMemberState",{memberId:bound.body.member.id,state:"disabled",revokeGrants:true,actor});expect(disabled.res.status).toBe(200);expect((await raw(t,"bindIdentity",{clerkUserId:"u_member",emails:["member@example.com"]})).res.status).toBe(409);expect((await raw(t,"gateBrowser",{clerkUserId:"u_member",epoch:0,service:"missing"})).body.allowed).toBe(false);});
it("preserves the last active owner and permits ownership transfer",async()=>{const t=tenant();const boot=await bootstrap(t);actor.memberId=boot.body.members[0].id;expect((await raw(t,"setMemberRole",{memberId:actor.memberId,role:"admin",actor})).res.status).toBe(409);const invited=await raw(t,"inviteMember",{email:"second@example.com",role:"admin",actor});const bound=await raw(t,"bindIdentity",{clerkUserId:"u_second",emails:["second@example.com"]});expect((await raw(t,"setMemberRole",{memberId:bound.body.member.id,role:"owner",actor})).res.status).toBe(200);expect((await raw(t,"setMemberRole",{memberId:actor.memberId,role:"admin",actor})).res.status).toBe(200);expect(invited.body.member.role).toBe("admin");});
it("rejects malformed bootstrap snapshots before writing the migration marker",async()=>{const t=tenant();const bad=await raw(t,"bootstrapMembers",{displayName:"Bad",bootstrappedFrom:"fresh",claimantClerkUserId:"u_owner",members:[{clerkUserId:"u_owner",email:"same@example.com",role:"owner",state:"active"},{clerkUserId:"u_other",email:"SAME@example.com",role:"member",state:"active"}]});expect(bad.res.status).toBe(409);const context=await raw(t,"memberContext",{clerkUserId:"someone_else"});expect(context.body.tenantMeta).toBeNull();});
it("revoking membership grants preserves non-service destinations",async()=>{const t=tenant();const boot=await bootstrap(t);const owner={clerkUserId:"u_owner",memberId:boot.body.members[0].id,label:"owner@example.com"};await raw(t,"enroll",{name:"svc"});const invited=await raw(t,"inviteMember",{email:"member@example.com",role:"member",actor:owner});await raw(t,"bindIdentity",{clerkUserId:"u_member",emails:["member@example.com"]});await raw(t,"addAcl",{src:{type:"user",name:"member@example.com"},dst:[{type:"service",name:"svc"},{type:"tag",name:"ops"}]});await raw(t,"removeMember",{memberId:invited.body.member.id,revokeGrants:true,actor:owner});const state=await raw(t,"getState");const rule=state.body.acl.find((row:any)=>row.src?.name==="member@example.com");expect(rule?.dst).toEqual([{type:"tag",name:"ops"}]);});
it("forbids self-disable and self-removal while preserving owner self-demotion",async()=>{const t=tenant();const boot=await raw(t,"bootstrapMembers",{kind:"team",displayName:"Team",bootstrappedFrom:"fresh",claimantClerkUserId:"u_owner",members:[{clerkUserId:"u_owner",email:"owner@example.com",role:"owner",state:"active"},{clerkUserId:"u_second",email:"second@example.com",role:"owner",state:"active"},{clerkUserId:"u_admin",email:"admin@example.com",role:"admin",state:"active"}]});const owner={clerkUserId:"u_owner",memberId:boot.body.members[0].id,label:"owner@example.com"};const admin={clerkUserId:"u_admin",memberId:boot.body.members[2].id,label:"admin@example.com"};expect((await raw(t,"setMemberState",{memberId:owner.memberId,state:"disabled",actor:owner})).res.status).toBe(409);expect((await raw(t,"removeMember",{memberId:owner.memberId,actor:owner})).res.status).toBe(409);expect((await raw(t,"setMemberState",{memberId:admin.memberId,state:"disabled",actor:admin})).res.status).toBe(409);expect((await raw(t,"removeMember",{memberId:admin.memberId,actor:admin})).res.status).toBe(409);expect((await raw(t,"setMemberRole",{memberId:owner.memberId,role:"admin",actor:owner})).res.status).toBe(200);});
it("treats authorized same-role updates as no-op successes",async()=>{const t=tenant();const boot=await bootstrap(t);const owner={clerkUserId:"u_owner",memberId:boot.body.members[0].id,label:"owner@example.com"};const before=await raw(t,"getState");const replay=await raw(t,"setMemberRole",{memberId:owner.memberId,role:"owner",actor:owner});const after=await raw(t,"getState");expect(replay.res.status).toBe(200);expect(after.body.tenant.membershipVersion).toBe(before.body.tenant.membershipVersion);expect(after.body.logs).toHaveLength(before.body.logs.length);});
it("audits successful role, state, removal, and bootstrap mutations",async()=>{const t=tenant();const boot=await bootstrap(t);const owner={clerkUserId:"u_owner",memberId:boot.body.members[0].id,label:"owner@example.com"};const invited=await raw(t,"inviteMember",{email:"member@example.com",role:"member",actor:owner});await raw(t,"bindIdentity",{clerkUserId:"u_member",emails:["member@example.com"]});const before=(await raw(t,"getState")).body.logs.length;await raw(t,"setMemberRole",{memberId:invited.body.member.id,role:"admin",actor:owner});await raw(t,"setMemberState",{memberId:invited.body.member.id,state:"disabled",actor:owner});await raw(t,"setMemberState",{memberId:invited.body.member.id,state:"active",actor:owner});await raw(t,"removeMember",{memberId:invited.body.member.id,actor:owner});const logs=(await raw(t,"getState")).body.logs.slice(0,4);expect(logs).toHaveLength(4);expect(logs.every((x:any)=>x.actor===owner.memberId&&x.target.includes(invited.body.member.id))).toBe(true);expect((await raw(t,"getState")).body.logs.length).toBe(before+4);});
it("enforces MAX_MEMBERS for approval-created invitations",async()=>{const t=tenant();const members=Array.from({length:200},(_,i)=>({clerkUserId:`u_${i}`,email:`u${i}@example.com`,role:i===0?"owner":"member",state:"active"}));const boot=await raw(t,"bootstrapMembers",{kind:"team",displayName:"Full",bootstrappedFrom:"fresh",claimantClerkUserId:"u_0",members});const owner={clerkUserId:"u_0",memberId:boot.body.members[0].id,label:"u0@example.com"};await raw(t,"enroll",{name:"svc"});const request=await raw(t,"requestAccess",{email:"outsider@example.com",service:"svc"});const approved=await raw(t,"approveAccess",{id:request.body.request.id,actor:owner});expect(approved.res.status).toBe(409);const state=await raw(t,"getState");expect(state.body.members).toHaveLength(200);expect(state.body.accessRequests.find((r:any)=>r.id===request.body.request.id).status).toBe("pending");});
});
